//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salam.lk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataField
    {
        public int DataFieldID { get; set; }
        public string DataFieldName { get; set; }
        public int EntityTypeID { get; set; }
        public int DataTypeID { get; set; }
    }
}
