//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salam.lk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int EntityID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int EntityTypeID { get; set; }
        public string EntityName { get; set; }
        public string Data { get; set; }
    }
}
