//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salam.lk.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SLMEntities : DbContext
    {
        public SLMEntities()
            : base("name=SLMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataField> DataFields { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
    
        public virtual ObjectResult<searchEntity_Result> searchEntity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchEntity_Result>("searchEntity");
        }
    }
}
